[platformio]
default_envs = xiao_nrf52840_sense

[env:xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git#a33b13986ff07f32c9940006518fa130bb3ffd7f
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3@2.0.7
